<<<<<<< HEAD
spring.application.name=Proizvodstvo2

spring.datasource.url=jdbc:postgresql://localhost:5432/Example2
spring.datasource.username=postgres
spring.datasource.password=5748
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
=======
spring.application.name=ForProizvodsta

spring.datasource.url=jdbc:postgresql://localhost:5432/Example
spring.datasource.username=postgres
spring.datasource.password=5748
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

>>>>>>> c50a53a3ad84d202754c002251b301b02e3f8d63
