spring.application.name=ForProizvodsta

spring.datasource.url=jdbc:postgresql://localhost:5432/Example
spring.datasource.username=postgres
spring.datasource.password=5748
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

