spring.application.name=ForProizvodsta

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/EducationalDB  
spring.datasource.username=postgres  
spring.datasource.password=5748 

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true